/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_SMWindowutil (void);
GtkWidget* create_SMWindowAjout (void);
GtkWidget* create_SMWindowLogin (void);
GtkWidget* create_SMwindowmodifierr (void);
GtkWidget* create_SMwindowinscrii (void);
GtkWidget* create_SMAccueil (void);
GtkWidget* create_SMbienajout (void);
GtkWidget* create_SMbiensupp (void);
GtkWidget* create_AMWindowutil (void);
GtkWidget* create_AMWindowAjout (void);
GtkWidget* create_AMwindowmodifierr (void);
GtkWidget* create_AMwindowetudd (void);
GtkWidget* create_DBwindowajout (void);
GtkWidget* create_DBwindowpp (void);
GtkWidget* create_DBwindowmodif (void);
GtkWidget* create_DBwindowstat (void);
GtkWidget* create_page_principale (void);
GtkWidget* create_ajout_de_la_reclamation (void);
GtkWidget* create_modification_de_la_reclamation (void);
GtkWidget* create_statistique (void);
GtkWidget* create_windowpp (void);
GtkWidget* create_windowajout (void);
GtkWidget* create_windowmodif (void);
GtkWidget* create_windowstat (void);
GtkWidget* create_AZwindowfire (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window4 (void);
GtkWidget* create_windowahmedpp (void);
GtkWidget* create_windowahmedajout (void);
GtkWidget* create_windowahmedmodif (void);
GtkWidget* create_windowahmedstat (void);
GtkWidget* create_window5 (void);
GtkWidget* create_window7 (void);
