/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *SMWindowutil;
  GtkWidget *SMWindowAjout;
  
  GtkWidget *SMWindowLogin;
  GtkWidget *SMwindowmodifierr;
  GtkWidget *windowinscrii;
  GtkWidget *Accueil;
  GtkWidget *windowpp;
  GtkWidget *window5;


  

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*SMWindowutil = create_SMWindowutil ();
  gtk_widget_show (SMWindowutil);
  SMWindowAjout = create_SMWindowAjout ();
  gtk_widget_show (SMWindowAjout);*/
  
  SMWindowLogin = create_SMWindowLogin ();
  gtk_widget_show (SMWindowLogin);
  /*SMwindowmodifierr = create_SMwindowmodifierr ();
  gtk_widget_show (SMwindowmodifierr);
  windowinscrii = create_windowinscrii ();
  gtk_widget_show (windowinscrii);
  windowpp = create_windowpp ();
  gtk_widget_show (windowpp);*/
 
  

  gtk_main ();
  return 0;
}

